version: "3.7"
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  frontend:
    build: ./front-web
    restart: always
    ports:
      - "5002:80"
